AWSTemplateFormatVersion: "2010-09-09"

Mappings:
    Environment:
        dev:
            InstanceType: "t2.micro"
        prod:
            InstanceType: "t2.small"

    Timezone:
        us-east-1:
            Timezone: "America/New_York"
        us-west-2:
            Timezone: "America/Los_Angeles"

Conditions:
    CreateResource: !Equals [true, false]

Resources:
    DummyResource:
        Type: "AWS::CloudFormation::Stack"
        Condition: CreateResource
