AWSTemplateFormatVersion: "2010-09-09"

Resources:
    StaticWebsiteBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub "static-website-${AWS::AccountId}-${AWS::Region}"
            WebsiteConfiguration:
                IndexDocument: index.html
            PublicAccessBlockConfiguration:
                BlockPublicAcls: false
                IgnorePublicAcls: false
                BlockPublicPolicy: false
                RestrictPublicBuckets: false

    StaticWebsiteBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref StaticWebsiteBucket
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - Sid: "PublicReadGetObject"
                      Effect: "Allow"
                      Principal: "*"
                      Action:
                          - "s3:GetObject"
                      Resource:
                          - !Sub "arn:aws:s3:::static-website-${AWS::AccountId}-${AWS::Region}/*"
